<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130914135416 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE house ADD number_heated_floors INT NOT NULL, ADD whats_unheated VARCHAR(255) DEFAULT NULL, CHANGE doors_type doors_type ENUM('old_wooden', 'old_metal', 'new_wooden', 'new_metal', 'other'), CHANGE windows_type windows_type ENUM('old_single_glass', 'old_double_glass', 'old_improved', 'semi_new_double_glass', 'new_double_glass', 'new_triple_glass'), CHANGE roof_type roof_type ENUM('flat', 'oblique', 'steep'), CHANGE ventilation_type ventilation_type ENUM('natural', 'mechanical', 'mechanical_recovery')");
        $this->addSql("ALTER TABLE wall DROP wall_type");
        $this->addSql("UPDATE house SET number_heated_floors = GREATEST(1, number_floors - (!is_ground_floor_heated + (roof_type != 'flat' && !is_attic_heated) + (has_basement && !is_basement_heated)))");
        $this->addSql("UPDATE house SET number_heated_floors = 1 WHERE number_heated_floors < 1");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE house DROP number_heated_floors, DROP whats_unheated, CHANGE doors_type doors_type VARCHAR(255) DEFAULT NULL, CHANGE windows_type windows_type VARCHAR(255) DEFAULT NULL, CHANGE roof_type roof_type VARCHAR(255) DEFAULT NULL, CHANGE ventilation_type ventilation_type VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE wall ADD wall_type ENUM('single', 'double', 'triple') NULL");
    }
}
