Feature: Energy balance calculation
  In order to get energy balance calculation
  as a human being
  I want to be able to come here, fill out the form and get that data in my face

  Scenario: Energy calculation for single house
    Given I am on homepage
     When I follow "Sprawdź swój dom!"
     Then I should see "Ile ciepła potrzebuje twój dom?"
    Given I select "Dom jednorodzinny wolnostojący" from "Rodzaj budynku"
    Given I select "1982" from "Rok budowy domu"
    Given I select "Węgiel kamienny" from "Czym ogrzewasz dom"
    Given I fill in "Moc kotła" with "15"
    Given I fill in "Zużycie opału ostatniej zimy" with "2.2"
    Given I fill in "Koszt zużytego opału" with "1600"
    Given I fill in "Temperatura w mieszkaniu zimą" with "21"
    Given I fill in "Twój adres e-mail" with "juzefwt@wp.pl"
      And I press "Dalej"
     Then I should see "Informacje na temat budynku"
    Given I fill in "Długość budynku" with "12"
    Given I fill in "Szerokość budynku" with "8"
    Given I fill in "Liczba pięter" with "3"
    Given I fill in "Liczba ogrzewanych pięter" with "2"
    Given I select "Pustak żużlobetonowy" from "calculation_walls_0_construction_layer_material"
    Given I fill in "calculation_walls_0_construction_layer_size" with "30"
    Given I select "Pustka powietrzna" from "calculation_walls_0_isolation_layer_material"
    Given I fill in "calculation_walls_0_isolation_layer_size" with "10"
    Given I select "Cegła dziurawka" from "calculation_walls_0_outside_layer_material"
    Given I fill in "calculation_walls_0_outside_layer_size" with "15"
    Given I select "Styropian" from "calculation_walls_0_extra_isolation_layer_material"
    Given I fill in "calculation_walls_0_extra_isolation_layer_size" with "6"
    Given I fill in "Liczba drzwi zewnętrznych" with "3"
    Given I select "Stare drewniane" from "Rodzaj drzwi zewnętrznych"
    Given I fill in "Liczba okien" with "12"
    Given I select "Nowe z szybami zespolonymi" from "Rodzaj okien"
    Given I check "Dom posiada balkon(y)"
    Given I select "płaski" from "Rodzaj dachu"
    Given I select "Trociny drzewne" from "calculation_highest_ceiling_isolation_layer_material"
    Given I fill in "calculation_highest_ceiling_isolation_layer_size" with "35"
    Given I check "Dom posiada garaż"
    Given I select "Styropian twardy" from "calculation_ground_floor_isolation_layer_material"
    Given I fill in "calculation_ground_floor_isolation_layer_size" with "4"
    Given I select "Naturalna lub grawitacyjna" from "Rodzaj wentylacji"
      And I press "Oblicz"
      And I should see "Budynek jednorodzinny trzypiętrowy"
      And I should see "Otwock i okolice"
      And I should see "Ściany: Pustak żużlobetonowy, 30cm + Pustka powietrzna, 10cm + Cegła dziurawka, 15cm + Styropian, 6cm"
      And I should see "Sprawność twojej instalacji grzewczej"
      And I should see "Edytuj informacje o budynku"

  Scenario: Energy calculation for double house
    Given I am on homepage
     When I follow "Sprawdź swój dom!"
     Then I should see "Ile ciepła potrzebuje twój dom?"
    Given I select "Bliźniak" from "Rodzaj budynku"
    Given I select "1982" from "Rok budowy domu"
    Given I select "Nie wiem" from "Czym ogrzewasz dom"
    Given I fill in "Temperatura w mieszkaniu zimą" with "21"
    Given I fill in "Twój adres e-mail" with "juzefwt@wp.pl"
      And I press "Dalej"
     Then I should see "Informacje na temat budynku"
    Given I fill in "Długość budynku" with "12"
    Given I fill in "Szerokość budynku" with "8"
    Given I fill in "Liczba pięter" with "3"
    Given I fill in "Liczba ogrzewanych pięter" with "2"
    Given I select "Pustak żużlobetonowy" from "calculation_walls_0_construction_layer_material"
    Given I fill in "calculation_walls_0_construction_layer_size" with "30"
    Given I select "Pustka powietrzna" from "calculation_walls_0_isolation_layer_material"
    Given I fill in "calculation_walls_0_isolation_layer_size" with "10"
    Given I select "Cegła dziurawka" from "calculation_walls_0_outside_layer_material"
    Given I fill in "calculation_walls_0_outside_layer_size" with "15"
    Given I select "Styropian" from "calculation_walls_0_extra_isolation_layer_material"
    Given I fill in "calculation_walls_0_extra_isolation_layer_size" with "6"
    Given I fill in "Liczba drzwi zewnętrznych" with "3"
    Given I select "Stare drewniane" from "Rodzaj drzwi zewnętrznych"
    Given I fill in "Liczba okien" with "12"
    Given I select "Nowe z szybami zespolonymi" from "Rodzaj okien"
    Given I check "Dom posiada balkon(y)"
    Given I select "płaski" from "Rodzaj dachu"
    Given I select "Trociny drzewne" from "calculation_highest_ceiling_isolation_layer_material"
    Given I fill in "calculation_highest_ceiling_isolation_layer_size" with "35"
    Given I check "Dom posiada garaż"
    Given I select "Styropian twardy" from "calculation_ground_floor_isolation_layer_material"
    Given I fill in "calculation_ground_floor_isolation_layer_size" with "4"
    Given I select "Naturalna lub grawitacyjna" from "Rodzaj wentylacji"
      And I press "Oblicz"
      And I should see "Nie wiemy nic o tym jak aktualnie ogrzewasz"
      And I should see "Bliźniak trzypiętrowy"
      And I should see "Otwock i okolice"
      And I should see "Ściany: Pustak żużlobetonowy, 30cm + Pustka powietrzna, 10cm + Cegła dziurawka, 15cm + Styropian, 6cm"
      And I should see "Niestety nie podałeś kosztów ogrzewania"
      And I should see "Edytuj informacje o budynku"

  Scenario: Energy calculation for apartment
    Given I am on homepage
     When I follow "Sprawdź swój dom!"
     Then I should see "Ile ciepła potrzebuje twój dom?"
    Given I select "Mieszkanie" from "Rodzaj budynku"
    Given I select "1999" from "Rok budowy domu"
    Given I select "Prąd elektryczny" from "Czym ogrzewasz dom"
    Given I fill in "Temperatura w mieszkaniu zimą" with "22"
      And I press "Dalej"
     Then I should see "Informacje na temat mieszkania"
    Given I fill in "Długość mieszkania" with "8"
    Given I fill in "Szerokość mieszkania" with "8"
    Given I fill in "Liczba pięter" with "1"
    Given I fill in "Liczba ogrzewanych pięter" with "1"
    Given I select "Ogrzewany lokal" from "Co znajduje się nad"
    Given I select "Ogrzewany lokal" from "Co znajduje się pod"
    Given I fill in "Liczba ścian zewnętrznych" with "2"
    Given I fill in "Liczba ścian nieogrzewanych" with "1"
    Given I select "Beton komórkowy" from "calculation_walls_0_construction_layer_material"
    Given I fill in "calculation_walls_0_construction_layer_size" with "35"
    Given I select "Styropian" from "calculation_walls_0_extra_isolation_layer_material"
    Given I fill in "calculation_walls_0_extra_isolation_layer_size" with "10"
    Given I fill in "Liczba drzwi zewnętrznych" with "0"
    Given I fill in "Liczba okien" with "3"
    Given I select "Nowe z szybami zespolonymi" from "Rodzaj okien"
    Given I select "Naturalna lub grawitacyjna" from "Rodzaj wentylacji"
      And I press "Oblicz"
     Then I should see "Twój dom jest niskoenergetyczny"
      And I should see "Nie wiemy nic o tym jak aktualnie ogrzewasz"
      And I should see "Mieszkanie 1-poziomowe"
      And I should see "Otwock i okolice"
      And I should see "Ściany: Beton komórkowy, 35cm + Styropian, 10cm"
      And I should see "Piętro wyżej: ogrzewany lokal, piętro niżej: ogrzewany lokal"
      And I should see "Niestety nie podałeś kosztów ogrzewania"
      And I should see "Zapomnij o kotle węglowym"
      And I should see "Edytuj informacje o budynku"
